import type { Difficulty, GeneratorMeta, Question } from './types';
import type { Rng } from './rng';

export const CONSTRUCTED_SESSION_SIZE = 3;
export const CONSTRUCTED_TOPICS: (GeneratorMeta & { subject: 'math' | 'english' | 'chinese' })[] = [
  { id: 'math-reasoning-studio', subject: 'math', icon: '🧠', name: { en: 'Maths Reasoning Studio', zh: '数学思考练习' }, term: 2 },
  { id: 'english-writing-studio', subject: 'english', icon: '✏️', name: { en: 'English Writing Studio', zh: '英语写作练习' } },
  { id: 'chinese-writing-studio', subject: 'chinese', icon: '🖊️', name: { en: 'Chinese Writing Studio', zh: '华文写作练习' } },
];

type Draft = Omit<Question, 'id' | 'kind' | 'topic' | 'answer'> & { prompt: Question['prompt']; model: Question['prompt']; criteria: Question['prompt'][] };

const MATH: Draft[] = [
  { difficulty: 'standard', prompt: { en: 'A canteen has 96 curry puffs. It packs 8 on each plate. Explain how to find the number of plates.', zh: '食堂有96个咖喱角，每盘放8个。说明怎样求盘子的数量。' }, model: { en: 'I divide 96 by 8 because the puffs are shared equally. 96 ÷ 8 = 12, so 12 plates are needed.', zh: '因为要平均分，所以我用96除以8。96 ÷ 8 = 12，因此需要12个盘子。' }, criteria: [{ en: 'I chose division and explained why.', zh: '我选择除法，并说明原因。' }, { en: 'I showed 96 ÷ 8 = 12.', zh: '我写出96 ÷ 8 = 12。' }, { en: 'I answered with the unit “plates”.', zh: '我的答案写了单位“盘”。' }] },
  { difficulty: 'standard', prompt: { en: 'Mei has RM50. She buys a book for RM18 and a ruler for RM4. Explain how much money remains.', zh: '美有RM50。她买了一本RM18的书和一把RM4的尺。说明她还剩多少钱。' }, model: { en: 'The total spent is RM18 + RM4 = RM22. RM50 − RM22 = RM28, so RM28 remains.', zh: '总花费是RM18 + RM4 = RM22。RM50 − RM22 = RM28，所以还剩RM28。' }, criteria: [{ en: 'I found the total spent.', zh: '我先求出总花费。' }, { en: 'I subtracted it from RM50.', zh: '我从RM50减去总花费。' }, { en: 'I used RM in the answer.', zh: '答案中写了RM。' }] },
  { difficulty: 'standard', prompt: { en: 'A ribbon is 2 m long. Farah uses 75 cm. Explain how much ribbon is left in centimetres.', zh: '一条丝带长2米。法拉用了75厘米。说明还剩多少厘米。' }, model: { en: 'First convert 2 m to 200 cm. Then 200 − 75 = 125, so 125 cm is left.', zh: '先把2米换算成200厘米，再算200 − 75 = 125，所以还剩125厘米。' }, criteria: [{ en: 'I converted metres to centimetres.', zh: '我把米换算成厘米。' }, { en: 'I showed the subtraction.', zh: '我写出减法算式。' }, { en: 'I gave the answer in centimetres.', zh: '我用厘米作答。' }] },
  { difficulty: 'standard', prompt: { en: 'A class collected 24 cans on Monday and 31 on Tuesday. Explain whether 60 cans were collected altogether.', zh: '一个班星期一收集24个罐子，星期二收集31个。说明两天是否共收集60个。' }, model: { en: '24 + 31 = 55. Since 55 is less than 60, they did not collect 60 cans; they were short by 5.', zh: '24 + 31 = 55。55少于60，所以没有达到60个，还差5个。' }, criteria: [{ en: 'I added both days.', zh: '我把两天的数量相加。' }, { en: 'I compared 55 with 60.', zh: '我比较55和60。' }, { en: 'I stated a clear conclusion.', zh: '我写出清楚的结论。' }] },
  { difficulty: 'standard', prompt: { en: 'Three pupils share 2 identical pizzas equally. Explain what fraction of a pizza each pupil gets.', zh: '三名学生平均分享两个同样大小的比萨。说明每人得到一个比萨的几分之几。' }, model: { en: 'Each pizza can be cut into 3 equal parts, making 6 thirds. Each pupil gets 2 thirds, so each gets 2/3 of a pizza.', zh: '每个比萨切成3等份，共有6个三分之一。每人得到2份，所以每人得到一个比萨的2/3。' }, criteria: [{ en: 'I described equal sharing.', zh: '我说明了平均分享。' }, { en: 'I gave the fraction 2/3.', zh: '我写出分数2/3。' }, { en: 'I referred to one whole pizza.', zh: '我说明是一个完整比萨的几分之几。' }] },
  { difficulty: 'advanced', prompt: { en: 'A school orders 7 boxes of 36 pencils and gives 198 pencils to pupils. Explain how many pencils remain.', zh: '学校订购7盒铅笔，每盒36支，并派发198支。说明还剩多少支。' }, model: { en: 'First find the total: 7 × 36 = 252. Then subtract those given out: 252 − 198 = 54. There are 54 pencils left.', zh: '先求总数：7 × 36 = 252。再减去已派发的：252 − 198 = 54。还剩54支铅笔。' }, criteria: [{ en: 'I used multiplication to find the total.', zh: '我用乘法求总数。' }, { en: 'I subtracted 198.', zh: '我减去198。' }, { en: 'My answer includes the unit.', zh: '答案写了单位。' }] },
  { difficulty: 'advanced', prompt: { en: 'A bus leaves at 14:35 and arrives at 16:10. Explain how long the journey takes.', zh: '巴士在14时35分出发，16时10分抵达。说明车程用了多久。' }, model: { en: 'From 14:35 to 15:35 is 1 hour. From 15:35 to 16:10 is 35 minutes. The journey takes 1 hour 35 minutes.', zh: '14时35分到15时35分是1小时，15时35分到16时10分是35分钟。车程共1小时35分钟。' }, criteria: [{ en: 'I split the elapsed time into clear steps.', zh: '我把经过时间分成清楚的步骤。' }, { en: 'I combined hours and minutes correctly.', zh: '我正确合并小时和分钟。' }, { en: 'I stated 1 hour 35 minutes.', zh: '我写出1小时35分钟。' }] },
  { difficulty: 'advanced', prompt: { en: 'A recipe for 4 people uses 600 mL of milk. Explain how much milk is needed for 10 people at the same rate.', zh: '四人份的食谱需要600毫升牛奶。说明按相同比率准备十人份需要多少牛奶。' }, model: { en: 'For 1 person: 600 ÷ 4 = 150 mL. For 10 people: 150 × 10 = 1,500 mL. So 1,500 mL is needed.', zh: '一人份：600 ÷ 4 = 150毫升。十人份：150 × 10 = 1,500毫升。所以需要1,500毫升。' }, criteria: [{ en: 'I found the amount for one person.', zh: '我先求一人份的数量。' }, { en: 'I multiplied by 10.', zh: '我再乘以10。' }, { en: 'I used the correct unit.', zh: '我用了正确的单位。' }] },
  { difficulty: 'advanced', prompt: { en: 'A rectangle has perimeter 30 cm and length 9 cm. Explain how to find its width.', zh: '一个长方形的周长是30厘米，长是9厘米。说明怎样求它的宽。' }, model: { en: 'Length + width is half the perimeter: 30 ÷ 2 = 15 cm. Width = 15 − 9 = 6 cm.', zh: '长加宽是周长的一半：30 ÷ 2 = 15厘米。宽 = 15 − 9 = 6厘米。' }, criteria: [{ en: 'I halved the perimeter.', zh: '我先把周长除以2。' }, { en: 'I subtracted the length.', zh: '我减去长。' }, { en: 'I stated 6 cm.', zh: '我写出6厘米。' }] },
  { difficulty: 'advanced', prompt: { en: 'A pupil says 3/4 is smaller than 2/3 because fourths are smaller pieces than thirds. Explain the mistake.', zh: '一名学生说3/4小于2/3，因为四分之一比三分之一小。说明他的错误。' }, model: { en: 'The size of one part is not enough; we must also consider how many parts are taken. Use twelfths: 3/4 = 9/12 and 2/3 = 8/12, so 3/4 is larger.', zh: '只比较每一份的大小并不够，还要看取了多少份。化成十二分数：3/4 = 9/12，2/3 = 8/12，所以3/4较大。' }, criteria: [{ en: 'I explained why comparing one part is not enough.', zh: '我说明为什么只比较一份并不足够。' }, { en: 'I used equivalent fractions or another valid model.', zh: '我用等值分数或其他正确方法。' }, { en: 'I concluded that 3/4 is larger.', zh: '我说明3/4较大。' }] },
];

const ENGLISH: Draft[] = [
  { difficulty: 'standard', prompt: { en: 'Write 3–4 sentences about your favourite place at school.', zh: '用3至4个英语句子写你在学校最喜欢的地方。' }, model: { en: 'My favourite place at school is the library. It is quiet and bright. I enjoy reading adventure books there with my friends.', zh: '示例：My favourite place at school is the library. It is quiet and bright. I enjoy reading adventure books there with my friends.' }, criteria: [{ en: 'I named the place.', zh: '我写出地点。' }, { en: 'I gave at least two details.', zh: '我写了至少两个细节。' }, { en: 'My sentences begin with capitals and end correctly.', zh: '句子以大写字母开头，并有正确的句末标点。' }] },
  { difficulty: 'standard', prompt: { en: 'Write a short message to tell your friend that football practice has moved to 4:00 p.m.', zh: '写一则英语短讯，告诉朋友足球练习改到下午4时。' }, model: { en: 'Hi Amir, football practice has moved to 4:00 p.m. today. Please meet us at the school field. See you!', zh: '示例：Hi Amir, football practice has moved to 4:00 p.m. today. Please meet us at the school field. See you!' }, criteria: [{ en: 'I stated the new time.', zh: '我写出新的时间。' }, { en: 'I made the purpose clear.', zh: '短讯目的清楚。' }, { en: 'I used a suitable greeting or ending.', zh: '我用了合适的称呼或结尾。' }] },
  { difficulty: 'standard', prompt: { en: 'Write 3–4 sentences about how you help at home.', zh: '用3至4个英语句子写你如何在家帮忙。' }, model: { en: 'I help my family after dinner. I clear the table and wash the cups. Then I put the clean dishes away.', zh: '示例：I help my family after dinner. I clear the table and wash the cups. Then I put the clean dishes away.' }, criteria: [{ en: 'I described actions I do.', zh: '我描述了自己做的事情。' }, { en: 'I used present-tense verbs.', zh: '我用了现在时态动词。' }, { en: 'My ideas are in a clear order.', zh: '内容次序清楚。' }] },
  { difficulty: 'standard', prompt: { en: 'Write a polite note asking your teacher for help with a maths question.', zh: '写一则有礼貌的英语便条，请老师协助解答一道数学题。' }, model: { en: 'Dear Ms Tan, I do not understand Question 5. Could you please explain it to me? Thank you.', zh: '示例：Dear Ms Tan, I do not understand Question 5. Could you please explain it to me? Thank you.' }, criteria: [{ en: 'I explained what help I need.', zh: '我说明需要什么帮助。' }, { en: 'I used polite words.', zh: '我使用有礼貌的用语。' }, { en: 'I included a greeting or thanks.', zh: '我写了称呼或谢语。' }] },
  { difficulty: 'standard', prompt: { en: 'Write 3–4 sentences describing a rainy morning.', zh: '用3至4个英语句子描写一个下雨的早晨。' }, model: { en: 'Dark clouds covered the sky. Rain tapped loudly on the windows. I wore my raincoat and walked carefully under my umbrella.', zh: '示例：Dark clouds covered the sky. Rain tapped loudly on the windows. I wore my raincoat and walked carefully under my umbrella.' }, criteria: [{ en: 'I described what could be seen or heard.', zh: '我描写了看到或听到的事物。' }, { en: 'I used complete sentences.', zh: '我用了完整句子。' }, { en: 'I checked capitals and punctuation.', zh: '我检查了大写字母和标点。' }] },
  { difficulty: 'advanced', prompt: { en: 'Write 5–6 sentences about a time you solved a problem with a friend.', zh: '用5至6个英语句子写你和朋友一起解决问题的一次经历。' }, model: { en: 'During art class, Siti and I could not find our blue paint. We checked our bags and asked our group. Then Siti suggested mixing green and purple decorations instead. We finished the poster together. It still looked cheerful, and we learnt to prepare our materials earlier.', zh: '示例说明问题、行动、结果和感受；答案可与示例不同。' }, criteria: [{ en: 'I explained the problem.', zh: '我交代了问题。' }, { en: 'I described what we did and what happened.', zh: '我描述了解决方法和结果。' }, { en: 'I linked ideas with words such as then, because or so.', zh: '我用then、because或so等词连接内容。' }] },
  { difficulty: 'advanced', prompt: { en: 'Write an email of 5–6 sentences inviting a cousin to a school carnival.', zh: '写一封5至6句的英语电邮，邀请表亲参加学校嘉年华。' }, model: { en: 'Hi Jia Wei, my school carnival is this Saturday from 9:00 a.m. to 1:00 p.m. There will be games, food stalls and a book sale. Would you like to come with me? Please bring a hat because some activities are outdoors. I hope you can join us!', zh: '示例包括活动、日期时间、详情和邀请；答案可与示例不同。' }, criteria: [{ en: 'I included the event, day and time.', zh: '我写出活动、日期和时间。' }, { en: 'I gave useful details.', zh: '我提供了有用的详情。' }, { en: 'I made a clear invitation and used email conventions.', zh: '我清楚提出邀请，并使用电邮格式。' }] },
  { difficulty: 'advanced', prompt: { en: 'Write 5–6 sentences explaining how to keep the classroom clean.', zh: '用5至6个英语句子说明如何保持课室清洁。' }, model: { en: 'First, put rubbish in the correct bin. Wipe your table after an activity. Return books and tools to their places. Work with your classmates during cleaning duty. A tidy classroom is safer and more pleasant for everyone.', zh: '示例按次序提出具体方法，并说明好处；答案可与示例不同。' }, criteria: [{ en: 'I gave at least three practical steps.', zh: '我提出至少三个实际步骤。' }, { en: 'I organised the steps clearly.', zh: '步骤安排清楚。' }, { en: 'I explained why cleanliness matters.', zh: '我说明保持清洁的重要性。' }] },
  { difficulty: 'advanced', prompt: { en: 'Continue this story in 5–6 sentences: “When I opened the box, I heard a tiny sound...”', zh: '用5至6个英语句子续写故事：“When I opened the box, I heard a tiny sound...”' }, model: { en: 'A small kitten looked up at me. It was cold and hungry, so I wrapped it in a towel. My mother helped me give it some water. We called the animal shelter to find its owner. I felt relieved when the kitten was safe.', zh: '示例有连贯的事件、适当结尾和感受；故事内容可以不同。' }, criteria: [{ en: 'My events follow a logical order.', zh: '事情发展次序合理。' }, { en: 'I used descriptive words or feelings.', zh: '我使用描写词语或感受。' }, { en: 'My story has an ending.', zh: '故事有结尾。' }] },
  { difficulty: 'advanced', prompt: { en: 'Write 5–6 sentences comparing learning from a book and learning from a video.', zh: '用5至6个英语句子比较从书本和影片中学习。' }, model: { en: 'Books let me read slowly and return to difficult parts. Videos can show movement and sound clearly. Both can teach the same topic in different ways. Each is useful for a different purpose. I prefer books for quiet revision, but I use videos when I need to see how something works.', zh: '示例写出两者特点、共同点和个人选择；答案可与示例不同。' }, criteria: [{ en: 'I described both books and videos.', zh: '我写到书本和影片。' }, { en: 'I included a similarity or difference.', zh: '我写出相同点或不同点。' }, { en: 'I supported my preference with a reason.', zh: '我用理由支持自己的选择。' }] },
];

const CHINESE: Draft[] = [
  { difficulty: 'standard', prompt: { en: '以“我最喜欢的校园角落”为题，写三至四句话。', zh: '以“我最喜欢的校园角落”为题，写三至四句话。' }, model: { en: '我最喜欢学校的小花园。那里种着五颜六色的花，还常有蝴蝶飞来。我喜欢在休息时静静地观察它们。', zh: '我最喜欢学校的小花园。那里种着五颜六色的花，还常有蝴蝶飞来。我喜欢在休息时静静地观察它们。' }, criteria: [{ en: '点出一个校园地点。', zh: '点出一个校园地点。' }, { en: '写出至少两个具体细节。', zh: '写出至少两个具体细节。' }, { en: '句子完整，标点正确。', zh: '句子完整，标点正确。' }] },
  { difficulty: 'standard', prompt: { en: '写一则短讯，告诉同学明天要带水彩和画笔。', zh: '写一则短讯，告诉同学明天要带水彩和画笔。' }, model: { en: '嘉恩：明天的美术课要用水彩和画笔，请记得带来。谢谢！', zh: '嘉恩：明天的美术课要用水彩和画笔，请记得带来。谢谢！' }, criteria: [{ en: '写清楚要带的两样物品。', zh: '写清楚要带的两样物品。' }, { en: '交代时间是明天。', zh: '交代时间是明天。' }, { en: '称呼和语气合适。', zh: '称呼和语气合适。' }] },
  { difficulty: 'standard', prompt: { en: '用三至四句话写你怎样在家帮忙。', zh: '用三至四句话写你怎样在家帮忙。' }, model: { en: '吃过晚饭后，我帮忙收拾餐桌。我把碗碟放到洗碗盆里，再用布把桌面擦干净。妈妈称赞我是个好帮手。', zh: '吃过晚饭后，我帮忙收拾餐桌。我把碗碟放到洗碗盆里，再用布把桌面擦干净。妈妈称赞我是个好帮手。' }, criteria: [{ en: '写出自己做的事情。', zh: '写出自己做的事情。' }, { en: '内容有先后次序。', zh: '内容有先后次序。' }, { en: '使用完整句子。', zh: '使用完整句子。' }] },
  { difficulty: 'standard', prompt: { en: '写一张便条，有礼貌地请老师解释一道数学题。', zh: '写一张便条，有礼貌地请老师解释一道数学题。' }, model: { en: '陈老师：我不明白练习五的第三题。请问您可以再讲解一次吗？谢谢您。', zh: '陈老师：我不明白练习五的第三题。请问您可以再讲解一次吗？谢谢您。' }, criteria: [{ en: '说明不明白哪一题。', zh: '说明不明白哪一题。' }, { en: '使用礼貌用语。', zh: '使用礼貌用语。' }, { en: '便条格式清楚。', zh: '便条格式清楚。' }] },
  { difficulty: 'standard', prompt: { en: '用三至四句话描写下雨的早晨。', zh: '用三至四句话描写下雨的早晨。' }, model: { en: '清晨，乌云遮住了天空。雨点不停地敲打窗户，发出滴滴答答的声音。我穿上雨衣，小心地撑伞上学。', zh: '清晨，乌云遮住了天空。雨点不停地敲打窗户，发出滴滴答答的声音。我穿上雨衣，小心地撑伞上学。' }, criteria: [{ en: '写出看到或听到的景象。', zh: '写出看到或听到的景象。' }, { en: '使用合适的形容词或象声词。', zh: '使用合适的形容词或象声词。' }, { en: '句子通顺。', zh: '句子通顺。' }] },
  { difficulty: 'advanced', prompt: { en: '写五至六句话，记叙你和朋友一起解决问题的一次经历。', zh: '写五至六句话，记叙你和朋友一起解决问题的一次经历。' }, model: { en: '美术课时，我和丽婷找不到蓝色颜料。我们先检查书包，再询问组员，还是没有找到。丽婷建议改用绿色和紫色装饰海报。最后，海报依然很漂亮。我们也学会了上课前要检查用品。', zh: '美术课时，我和丽婷找不到蓝色颜料。我们先检查书包，再询问组员，还是没有找到。丽婷建议改用绿色和紫色装饰海报。最后，海报依然很漂亮。我们也学会了上课前要检查用品。' }, criteria: [{ en: '交代问题、解决方法和结果。', zh: '交代问题、解决方法和结果。' }, { en: '事情经过有清楚次序。', zh: '事情经过有清楚次序。' }, { en: '写出感受或学到的道理。', zh: '写出感受或学到的道理。' }] },
  { difficulty: 'advanced', prompt: { en: '写一封五至六句的电邮，邀请表哥参加学校嘉年华。', zh: '写一封五至六句的电邮，邀请表哥参加学校嘉年华。' }, model: { en: '志明表哥：这个星期六上午九时至下午一时，学校将举行嘉年华。现场有游戏、美食摊位和书展。你愿意和我一起参加吗？有些活动在户外进行，记得带帽子。我希望你能来！', zh: '志明表哥：这个星期六上午九时至下午一时，学校将举行嘉年华。现场有游戏、美食摊位和书展。你愿意和我一起参加吗？有些活动在户外进行，记得带帽子。我希望你能来！' }, criteria: [{ en: '写出活动、日期和时间。', zh: '写出活动、日期和时间。' }, { en: '提供有用的活动详情。', zh: '提供有用的活动详情。' }, { en: '邀请语气和电邮格式合适。', zh: '邀请语气和电邮格式合适。' }] },
  { difficulty: 'advanced', prompt: { en: '用五至六句话说明如何保持课室清洁。', zh: '用五至六句话说明如何保持课室清洁。' }, model: { en: '首先，我们要把垃圾丢进正确的垃圾桶。完成活动后，应该擦干净桌面。书本和用具也要放回原位。值日时，大家应互相合作。整洁的课室让我们学习得更安心。', zh: '首先，我们要把垃圾丢进正确的垃圾桶。完成活动后，应该擦干净桌面。书本和用具也要放回原位。值日时，大家应互相合作。整洁的课室让我们学习得更安心。' }, criteria: [{ en: '提出至少三个实际方法。', zh: '提出至少三个实际方法。' }, { en: '用连接词安排内容。', zh: '用连接词安排内容。' }, { en: '说明保持清洁的好处。', zh: '说明保持清洁的好处。' }] },
  { difficulty: 'advanced', prompt: { en: '续写五至六句话：“我打开纸箱时，里面传来微弱的声音……”', zh: '续写五至六句话：“我打开纸箱时，里面传来微弱的声音……”' }, model: { en: '一只小猫抬起头来看我。它又冷又饿，我赶紧用毛巾包住它。妈妈拿来清水，还和我一起联络动物收容所。后来，我们找到了小猫的主人。看见它平安回家，我终于放下心来。', zh: '一只小猫抬起头来看我。它又冷又饿，我赶紧用毛巾包住它。妈妈拿来清水，还和我一起联络动物收容所。后来，我们找到了小猫的主人。看见它平安回家，我终于放下心来。' }, criteria: [{ en: '情节衔接开头并合理发展。', zh: '情节衔接开头并合理发展。' }, { en: '加入动作、描写或感受。', zh: '加入动作、描写或感受。' }, { en: '故事有合适的结尾。', zh: '故事有合适的结尾。' }] },
  { difficulty: 'advanced', prompt: { en: '用五至六句话比较从书本和影片中学习。', zh: '用五至六句话比较从书本和影片中学习。' }, model: { en: '看书时，我可以慢慢阅读，也能回头重读不明白的部分。影片则能清楚呈现动作和声音。两者都能帮助我们学习，却各有特点。不同的学习任务适合不同的方式。我复习时喜欢看书，需要观察过程时会选择影片。', zh: '看书时，我可以慢慢阅读，也能回头重读不明白的部分。影片则能清楚呈现动作和声音。两者都能帮助我们学习，却各有特点。不同的学习任务适合不同的方式。我复习时喜欢看书，需要观察过程时会选择影片。' }, criteria: [{ en: '写出书本和影片各自的特点。', zh: '写出书本和影片各自的特点。' }, { en: '写出相同点或不同点。', zh: '写出相同点或不同点。' }, { en: '用理由支持自己的选择。', zh: '用理由支持自己的选择。' }] },
];

const BANKS: Record<string, Draft[]> = { 'math-reasoning-studio': MATH, 'english-writing-studio': ENGLISH, 'chinese-writing-studio': CHINESE };

export function isConstructedTopic(id: string): boolean { return id in BANKS; }
export function constructedSubject(id: string) { return CONSTRUCTED_TOPICS.find((topic) => topic.id === id)?.subject; }

function stablePromptId(text: string): string {
  let hash = 2166136261;
  for (const char of text) hash = Math.imul(hash ^ char.charCodeAt(0), 16777619);
  return (hash >>> 0).toString(36);
}

export function validateConstructedContent(): string[] {
  const errors: string[] = [];
  const ids = new Set<string>(); const prompts = new Set<string>(); const models = new Set<string>();
  for (const [topic, drafts] of Object.entries(BANKS)) for (const draft of drafts) {
    const id = `${topic}-${draft.difficulty}-${stablePromptId(draft.prompt.en)}`;
    if (ids.has(id)) errors.push(`Duplicate id: ${id}`); ids.add(id);
    if (prompts.has(draft.prompt.en)) errors.push(`Duplicate prompt: ${draft.prompt.en}`); prompts.add(draft.prompt.en);
    if (models.has(draft.model.en)) errors.push(`Duplicate model: ${draft.model.en}`); models.add(draft.model.en);
    if (draft.criteria.length < 3 || draft.criteria.some((item) => !item.en.trim() || !item.zh.trim())) errors.push(`${id}: incomplete criteria`);
    const englishRange = /Write (\d)[–-](\d) sentences/i.exec(draft.prompt.en);
    const chineseRange = /(?:写|续写)([三五])至([四六])句话/.exec(draft.prompt.zh);
    const range = englishRange ? [Number(englishRange[1]), Number(englishRange[2])] : chineseRange ? [{ 三: 3, 五: 5 }[chineseRange[1] as '三' | '五'], { 四: 4, 六: 6 }[chineseRange[2] as '四' | '六']] : null;
    if (range) {
      const text = topic === 'english-writing-studio' ? draft.model.en : draft.model.zh;
      const count = (text.match(topic === 'english-writing-studio' ? /[.!?](?:\s|$)/g : /[。！？]/g) ?? []).length;
      if (count < range[0] || count > range[1]) errors.push(`${id}: model has ${count} sentences, expected ${range[0]}-${range[1]}`);
    }
  }
  return errors;
}

export function generateConstructedSession(topic: string, difficulty: Difficulty, rng: Rng): Question[] {
  const pool = BANKS[topic]?.filter((item) => item.difficulty === difficulty);
  if (!pool || pool.length < CONSTRUCTED_SESSION_SIZE) throw new Error(`Unknown or incomplete self-review topic: ${topic}/${difficulty}`);
  return rng.shuffle(pool).slice(0, CONSTRUCTED_SESSION_SIZE).map((item) => ({
    id: `${topic}-${difficulty}-${stablePromptId(item.prompt.en)}`,
    kind: 'self-check', topic, difficulty, prompt: item.prompt,
    answer: item.model.en,
    selfReview: { modelAnswer: item.model, criteria: item.criteria },
  }));
}
